module.exports = [
  "Google",
  "Microsoft",
  "Amazon",
  "Meta",
  "Apple",
  "Tower Research Capital",
  "De Shaw & Co",
  "Arcesium",
  "Goldman Sachs",
  "Uber India",
  "Atlassian",
  "Adobe",
  "Salesforce",
  "ServiceNow",
  "Intuit",
  "Walmart Global Tech",
  "Linkedin India",
  "Flipkart",
  "PhonePe",
  "CRED",
  "Swiggy",
  "Razorpay",
  "Twilio",
  "GitLab",
  "Automattic",
  "HubSpot",
  "Affirm",
  "BrowserStack",
  "Zoho",
  "Motive",
  "Coinbase India",
  "CrowdStrike",
  "Airmeet",
  "Postman",
  "Expedia Group",
  "Rippling"
];
